version: '3'
services:
  server:
    container_name: citizens-back
    build: ./server
    ports:
      - '5000:5000'
    volumes:
      - ./server:/app
      - ./server:/node_modules
  front:
    container_name: citizens-front
    ports:
      - '4000:4000'
    build: ./client
    volumes:
      - ./client:/app
      - ./client:/node_modules
